name: "Build website"

inputs:
  SITE_FOLDER:
    required: true
  BASE_URL_PREFIX:
    required: true
  PREVIEW:
    required: false
    default: ""
  BRANCH:
    required: false
    default: "main"
  PYTHON_LIBS:
    required: false
    default: ""
  PLOTS:
    required: false
    default: ""
  LATEX:
    required: false
    default: false
  GNUPLOT:
    required: false
    default: false
  CLEAR_CACHE:
    required: true
  CACHE_KEY:
    required: true

runs:
  using: "composite"
  steps:
    # =========== #
    # CACHE SETUP #
    # =========== #

    - uses: actions/cache@v2
      with:
        path: |
              ${{ inputs.SITE_FOLDER }}/__cache
              ${{ inputs.SITE_FOLDER }}/__site
        key: ${{ runner.os }}-${{ inputs.CACHE_KEY }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ inputs.CACHE_KEY }}-

    # ============ #
    # DEPENDENCIES #
    # ============ #

    # Python
    - if: ${{ inputs.PYTHON_LIBS != '' }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - if: ${{ inputs.PYTHON_LIBS != '' }}
      run: |
           pip install ${{ inputs.PYTHON_LIBS }}
           export PYTHON=$(which python)
      shell: bash

    # Apt-get update if necessary
    - if: ${{ (inputs.PLOTS != '') || (inputs.LATEX) || (inputs.GNUPLOT) }}
      run: sudo apt-get update -qq
      shell: bash

    # QT dependencies for Plots with GR backend
    - if: ${{ inputs.PLOTS != '' }}
      name: Installing QT5 💻...
      run: sudo apt-get install -y qt5-default
      shell: bash

    # LaTeX* deps for PGFPlotsX etc
    - if: ${{ inputs.LATEX }}
      run: sudo apt install -y pdf2svg texlive-latex-base texlive-binaries texlive-pictures texlive-latex-extra texlive-luatex
      shell: bash

    # Gnuplot for Gaston etc
    - if: ${{ inputs.GNUPLOT }}
      run: sudo apt-get install -y gnuplot
      shell: bash

    # ================ #
    # BUILDING WEBSITE #
    # ================ #

    # Julia
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.7

    # Building website
    - run: ${{ inputs.PLOTS }} julia -e '
              using Pkg;
              isempty("${{ inputs.PYTHON_LIBS }}") || (Pkg.add("PyCall"); Pkg.build("PyCall"););
              Pkg.add(
                url="https://github.com/tlienart/Xranklin.jl",
                rev="${{ inputs.BRANCH }}"
                );
              using Xranklin;
              build("${{ inputs.SITE_FOLDER }}";
                    clear=${{ inputs.CLEAR_CACHE }},
                    prefix=joinpath(
                      "${{ inputs.BASE_URL_PREFIX }}",
                      "${{ inputs.PREVIEW }}"
                      )
                    );'
      shell: bash

    # ========== #
    # DEPLOYMENT #
    # ========== #

    # TTFX Experiment results
    - uses: actions/checkout@v2
      with:
        ref: gh-ttfx
        path: ttfx

    - run: rm -rf ${{ inputs.SITE_FOLDER }}/__site/ttfx
      shell: bash
      continue-on-error: true

    - run: mv ttfx/ttfx ${{ inputs.SITE_FOLDER }}/__site/.
      shell: bash
      continue-on-error: true

    # Deployment
    - run: touch ${{ inputs.SITE_FOLDER }}/__site/.nojekyll
      shell: bash

    - uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: ${{ inputs.SITE_FOLDER }}/__site
        TARGET-FOLDER: "${{ inputs.PREVIEW }}"
