name: Add latest tag
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
